connections.snowflake
account = "NNFGNNX-HUB51720"
user = "VINITHJ"
password = "Iminsnowflake31"
private_key_file = "../xxx/xxx.p8"
role="ACCOUNTADMIN"
warehouse="COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true

