[snowflake]
user = "VINITHJ"
password = "Iminsnowflake31"
account = "NNFGNNX-HUB51720"
warehouse="COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
authenticator = "externalbrowser"
role = "ACCOUNTADMIN"

